const $=s=>document.querySelector(s);
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({events:[{id:'silent-dawn',name:'Operation Silent Dawn',type:'Operation',date:new Date(Date.now()+86400000).toISOString(),description:'Sample briefing: deploy with your squad and await mission orders.',response:null,cancelled:false},{id:'training',name:'Combined Arms Training',type:'Training',date:new Date(Date.now()+3*86400000).toISOString(),description:'Sample training session for infantry and aviation personnel.',response:null,cancelled:false}],notifications:[]});
let state;try{state=JSON.parse(localStorage.getItem('505th-hub-v1'));if(!Array.isArray(state?.events)||!Array.isArray(state?.notifications))state=initial();}catch{state=initial();}
let page='home';let toastTimer;
const save=()=>{try{localStorage.setItem('505th-hub-v1',JSON.stringify(state));}catch{toast('Storage unavailable. Changes will last only for this session.');}};
function toast(message){$('#toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',6000);}
function notify(message){state.notifications.unshift({message,date:new Date().toISOString()});save();toast(message);}
const dateLabel=date=>new Date(date).toLocaleString(undefined,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
const upcoming=()=>state.events.filter(e=>!e.cancelled&&new Date(e.date)>new Date()).sort((a,b)=>new Date(a.date)-new Date(b.date));
function buttons(e){return e.cancelled?'':`<div class="actions"><button class="${e.response==='attending'?'primary':'secondary'}" data-response="attending" data-id="${escapeHtml(e.id)}" aria-pressed="${e.response==='attending'}">✓ Attend</button><button class="${e.response==='unavailable'?'primary':'secondary'}" data-response="unavailable" data-id="${escapeHtml(e.id)}" aria-pressed="${e.response==='unavailable'}">Cannot attend</button></div>`;}
function eventCard(e,hero=false){return `<article class="${hero?'hero':'card'}"><span class="badge ${e.cancelled?'cancelled':''}">${e.cancelled?'CANCELLED':escapeHtml(e.type.toUpperCase())}</span><h2>${escapeHtml(e.name)}</h2><div class="meta"><span>${escapeHtml(dateLabel(e.date))}</span><span>505th Expeditionary Force</span></div><p>${escapeHtml(e.description)}</p><div class="small">Your response: ${e.response==='attending'?'Attending':e.response==='unavailable'?'Cannot attend':'Not responded'}</div>${buttons(e)}</article>`;}
function intro(title,description){return `<div class="intro"><div class="eyebrow">505TH EXPEDITIONARY FORCE</div><h1>${title}</h1><p>${description}</p></div>`;}
function render(){
 const staff=$('#role').value==='staff';$('#staffNav').hidden=!staff;if(page==='staff'&&!staff)page='home';
 document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#breadcrumb').textContent=page.toUpperCase();
 const events=upcoming();let html='';
 if(page==='home')html=intro('Welcome to your unit hub.','Your next deployment, availability, and unit updates in one place.')+`<div class="stats"><div class="card"><div class="small">UPCOMING EVENTS</div><div class="stat">${events.length}</div><div class="small">Operations and training</div></div><div class="card"><div class="small">YOUR SIGN-UPS</div><div class="stat">${events.filter(e=>e.response==='attending').length}</div><div class="small">Upcoming events you plan to attend</div></div><div class="card"><div class="small">ACCOUNT</div><div class="stat">DEMO</div><div class="small">Local preview · no live member data</div></div></div>`+(events[0]?eventCard(events[0],true):'<div class="card">No upcoming events.</div>')+`<div class="grid"><section class="card"><h2>Unit noticeboard</h2><div class="notice"><h3>Welcome to 505th Hub</h3><p>This prototype saves your responses on this computer. Discord and website synchronisation will be added next.</p></div></section><section class="card"><h2>Stay informed</h2><p>Visual notifications and a persistent history will keep event updates easy to find.</p><button class="secondary" data-action="test">Test notification</button></section></div>`;
 if(page==='operations')html=intro('Operations & training','Set your availability. Sign-ups are separate from confirmed attendance.')+`<div class="grid">${[...state.events].sort((a,b)=>new Date(a.date)-new Date(b.date)).map(e=>eventCard(e)).join('')}</div>`;
 if(page==='record')html=renderDavyRecord();
 if(page==='notifications')html=intro('Notifications','A visible history of your local prototype activity.')+`<div class="card"><button class="secondary" data-action="test">Test notification</button>${state.notifications.length?state.notifications.map(n=>`<article class="event"><h3>${escapeHtml(n.message)}</h3><span class="small">${escapeHtml(dateLabel(n.date))}</span></article>`).join(''):'<p>No notifications yet. Respond to an event or send a test notification.</p>'}</div>`;
 if(page==='staff')html=intro('Command terminal','Staff preview only. These controls change sample events on this computer.')+`<div class="grid"><section class="card"><h2>Create a sample event</h2><form id="eventForm" class="form"><label>Event name<input name="name" required maxlength="100" placeholder="Operation name"></label><label>Type<select name="type"><option>Operation</option><option>Training</option><option>Unit meeting</option></select></label><label>Start time (your local timezone)<input name="date" type="datetime-local" required></label><label>Briefing<input name="description" required maxlength="500" placeholder="What members need to know"></label><button class="primary" type="submit">Create event</button></form></section><section class="card"><h2>Manage sample events</h2>${state.events.map(e=>`<article class="event"><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(dateLabel(e.date))}</p>${e.cancelled?'<span class="badge cancelled">CANCELLED</span>':`<button class="danger" data-cancel="${escapeHtml(e.id)}">Cancel event</button>`}</article>`).join('')}</section></div>`;
 $('#content').innerHTML=html;
}
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;
 if(button.dataset.page){page=button.dataset.page;render();}
 if(button.dataset.response){const e=state.events.find(e=>e.id===button.dataset.id);if(!e||e.cancelled)return;e.response=button.dataset.response;notify(`${e.name}: ${e.response==='attending'?'you are attending':'you cannot attend'}.`);render();}
 if(button.dataset.cancel&&$('#role').value==='staff'){const e=state.events.find(e=>e.id===button.dataset.cancel);if(!e||e.cancelled)return;e.cancelled=true;notify(`${e.name} has been cancelled.`);render();}
 if(button.dataset.action==='test'){notify('505th Hub test: your visual notification history is working.');render();if(window.hubDesktop){try{const sent=await window.hubDesktop.testNotification();toast(sent?'Custom 505th alert opened in the bottom-right corner.':'Custom alert is unavailable.');}catch{toast('Could not send a Windows notification. The update is saved in your history.');}}else toast('Browser preview: launch the desktop app to test Windows notifications.');}
});
document.addEventListener('submit',event=>{if(event.target.id!=='eventForm')return;event.preventDefault();if($('#role').value!=='staff')return;const data=new FormData(event.target);const date=new Date(data.get('date'));if(!Number.isFinite(date.getTime())||date<=new Date()){toast('Choose a future event time.');return;}const name=data.get('name').trim();const description=data.get('description').trim();if(!name||!description){toast('Enter an event name and briefing.');return;}state.events.push({id:crypto.randomUUID(),name,type:data.get('type'),date:date.toISOString(),description,response:null,cancelled:false});notify(`${name} was created locally. Discord is not connected yet.`);render();});
$('#role').addEventListener('change',render);render();

window.hubDesktop?.onOperations?.(()=>{page='operations';render();});


